### PR TITLE
fix "regen: command not found" issue

### PR DESCRIPTION
**Pull request by diman-io**
- use `source` instead of `.` (dot)
 - add +x to script
 - update documentation

### CODE REVIEW

**Comment by anilcse** [comment]
> * use `source` instead of `.` (dot)
> * add +x to script
> * update documentation

@diman-io bash uses `.`, what is your os and arch?

**Comment by diman-io** [comment]
Ubuntu 18, bash:
```
...
go/test/winbatch.go
go/test/writebarrier.go
go/test/zerodivide.go
./scripts/gen_val_keys.sh: line 27: go: command not found
-- Clear old regen data and install Regen-ledger and setup the node --
install regen-ledger:v0.6.0-alpha2
...
```
Dot is alias of `source` in bash. On `zsh` (default now on macos) dot isn't working. `source` is more universal, I think.

But `source` doesn't work too :((( Several guys wrote to me about this in Russian telegram group @regen_ru. May be because it is inside script, I don't know.

Ok, I made some change in new commit and tested it on clear Ubuntu 18 on Hetzner VPS. Now it's work fine
```
go/test/writebarrier.go
go/test/zerodivide.go
go version go1.15.2 linux/amd64
-- Clear old regen data and install Regen-ledger and setup the node --
install regen-ledger:v0.6.0-alpha2
Cloning into '/root/go/src/github.com/regen-network/regen-ledger'...
```

**Comment by anilcse** [comment]
> Ubuntu 18, bash:
> 
> ```
> ...
> go/test/winbatch.go
> go/test/writebarrier.go
> go/test/zerodivide.go
> ./scripts/gen_val_keys.sh: line 27: go: command not found
> -- Clear old regen data and install Regen-ledger and setup the node --
> install regen-ledger:v0.6.0-alpha2
> ...
> ```
> 
> Dot is alias of `source` in bash. On `zsh` (default now on macos) dot isn't working. `source` is more universal, I think.
> 
> But `source` doesn't work too :((( Several guys wrote to me about this in Russian telegram group @regen_ru. May be because it is inside script, I don't know.
> 
> Ok, I made some change in new commit and tested it on clear Ubuntu 18 on Hetzner VPS. Now it's work fine
> 
> ```
> go/test/writebarrier.go
> go/test/zerodivide.go
> go version go1.15.2 linux/amd64
> -- Clear old regen data and install Regen-ledger and setup the node --
> install regen-ledger:v0.6.0-alpha2
> Cloning into '/root/go/src/github.com/regen-network/regen-ledger'...
> ```

Looks like this solution is not complete. It doesn't work on restart

**Comment by diman-io** [comment]
> Looks like this solution is not complete. It doesn't work on restart

Could you please share your log with error?

**Pull request closed without merging**
